dist: trusty
sudo: false
os: linux

language: haskell
ghc:
  - "7.10"

cache:
  directories:
  - .cabal-sandbox

install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
script: cabal configure --enable-tests && cabal test --show-details=always

