dist: trusty
sudo: false
os: linux

language: haskell
cache:
  directories:
    - .cabal-sandbox

matrix:
  include:
  - ghc: "7.8"
    env: CACHE_NAME=CACHE7.8
    
  - ghc: "7.10"
    env: CACHE_NAME=CACHE7.10

  - ghc: "8.0"
    env: CACHE_NAME=CACHE8.0

  - ghc: "8.2"
    env: CACHE_NAME=CACHE8.2

install: cabal sandbox init &&
         git clone https://github.com/bos/criterion.git &&
         sed -i '/version/s/0$/1/' criterion/criterion.cabal &&
         cabal sandbox add-source criterion &&
         cabal install --only-dependencies --enable-tests --enable-benchmarks --disable-documentation --enable-library-stripping &&
         cabal sandbox hc-pkg list

script: cabal configure --enable-tests --enable-benchmarks &&
        cabal build lib:hs3 &&
        cabal build lib:hs3Storage &&
        cabal build exe:hs3Server &&
        cabal build exe:hs3Client &&
        cabal test --show-details=always &&
        cabal bench
