dist: trusty
sudo: false
os: linux

language: haskell
cache:
  directories:
    - .cabal-sandbox

matrix:
  include:
  - ghc: "7.6"
    env: CACHE_NAME=CACHE7.6

  - ghc: "7.8"
    env: CACHE_NAME=CACHE7.8
    
  - ghc: "7.10"
    env: CACHE_NAME=CACHE7.10

  - ghc: "8.0"
    env: CACHE_NAME=CACHE8.0

  - ghc: "8.2"
    env: CACHE_NAME=CACHE8.2

install : cabal sandbox init && git clone https://github.com/bos/criterion.git && cabal sandbox add-source criterion && cabal install --only-dependencies --enable-tests --enable-bench --disable-documentation
script: cabal configure --enable-tests && cabal test --show-details=always && cabal bench
